export const stories = [
  {
    key: '-NUC6RSXwH7rghVYSKIw',
    authorId: '-NUC6RW3eawD-Afqs7lE',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '-NUC6TZU5iUVMV6qeGAe',
    createdAt: 1682773493601,
    description:
      'Lời văn nhẹ nhàng, hài hước, An Tư Nguyên đã đem đến cho người đọc một tác phẩm hay có tên Phồn Hoa Rực Rỡ. Nhân vật nữ chính là một cô gái ít nói, nhưng đặc biệt cô ấy rất thích trai đẹp. Còn nam chính là một người con trai từng trải, có kinh nghiệm khi yêu.Hai nhân vật đối lập nhau, một người là cừu, một người là sói..Chuyện gì sẽ xảy ra khi cừu non nớt gặp phải sói ranh mãnh đây???',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDR1y3N9HZPqaw0igjL1w8LDjXO8MqsjAj11HeEgtyMfP0I3fSijDRzi7LyZP1yI0NT3QxjIyMAdqETYw==/phon-hoa-ruc-ro.jpg',
    listens: 0,
    slug: 'phon-hoa-ruc-ro',
    status: 'Full',
    title: 'Phồn Hoa Rực Rỡ',
    totalChaps: 17,
    type: 'story',
    updatedAt: 1682773493601,
  },
  {
    key: '-NUC6RShHWcZ4w1uoiSG',
    authorId: '-NUC6RWAExsPyVRFv3sk',
    categories: ['-NSrNAkAlb9k7ZZTdeq3', '-NSrJ_yRU38knd4rZG03'],
    chapsId: '-NUC6Tb7mqmxHaI_ZV_V',
    createdAt: 1682773493613,
    description:
      'Truyện có tên Mắt Trái của Đản Đản kể về nhân vật nữ chính vô cùng xinh đẹp nhưng lại hơi ngốc, dáng vẻ ngốc ngếch đó đã tạo nên một nét đáng yêu. Dù trong truyện có chút hư cấu nhưng nó lại mang tính giải trí cao.Anh- nhân vật nam chính đánh giá cô là một cô gái có bộ ngực to nhưng đầu óc lại ngu ngốc. Cô cũng thế, cô nhận xét anh là một kẻ ích kỷ, giả dối. Nhưng chuyện gì đến cũng đến, mưa dầm thấm đất...Trong truyện này, điều đặc biệt nhất mà tác giả muốn gửi đến bạn đọc là nhân vật nữ chính có thể nhìn thấy được... Nhưng thấy được điều gì thì các bạn đọc sẽ biết.',
    download: 0,
    image:
      'https://static.8cache.com/cover/eJwFwUeyqzgAAMATUUMOi1kQDRYmp-eNi4wQ2QgMp__dQ8f8xxouS8S3RuW1Jj9525B2ZeVPevNImHMEJO2lyFBDCawAoLT_FN1C_K8DbocUzcGdZd97Ywu-KX28sRMhFN7r369t13FHRdGAjfakF5Mfo59HLynqHD9Vilh6zXcmRjAKYK2TyTqi1f060742Wr3dO9SmmbbEbaSX5KKoOQ2zzy0G1Tbg42M-S_YyvpXpzNyMawR6gqIXhnjJD4KXxuF2RL2n5QhWZ62efqWGV0bO3i29iJjWVJDn_eNqz3KthTLDw8r5f93fYTv8DtjThskT3-xDB2-1B8cnQOzXxz7cLhBsRyOxy3ts7NKf9pSvlNhgEvidsFkin4XBK9bBQYiBI7vtUVA5BOq9HUhzng_DvMTUFFMnRlKScmb7xvlBduEcRvpKVjxj7VXkXoCzC7fC2IyE5obPVS6aZyKuYtY4njd_mhQRAeSSeOhvsQn4VZZ7rchsuxpVw19wIRrxrIfUwJih2nssTeFN2Gy5fHPpLiDDrHI-UaR4_tl3zORzr3PXwz_LdMgvlE-WTC7fa-F2rkE4SAE7Jr-xdn02OoMPoYZBOJVc1V-nFSxbl38Od_K3FmzqhjrhV5f6LXhEGRmo2jOKs_yFyazQzUy3JNYQmEV2Ji7pKKWvLCIeHLacWtCcWxZRz8PTX45J_th29eSwkZ0HPlaQOO8vfeatOFmw1P8_aYojOoam_wHOYuww/mat-trai.jpg',
    listens: 0,
    slug: 'mat-trai',
    status: 'Full',
    title: 'Mắt Trái',
    totalChaps: 18,
    type: 'story',
    updatedAt: 1682773493613,
  },
  {
    key: '-NUC6RSqhzWVjOHKJghQ',
    authorId: '-NUC6RWUbppFr2uj7xGA',
    categories: [
      '-NSrNAjzDYDbOTsTXFLH',
      '-NSrNAk52QfrZ0vo-BW2',
      '-NSrNAkDNPzkqrE_p03K',
      '-NSrNAkev1RsN2wlHsCP',
      '-NSrNAkrxmXmisl1A0w7',
      '-NSrNAmqxsa9v8x6swUB',
      '-NSrNAnoka6AvRqtOWlq',
    ],
    chapsId: '',
    createdAt: 1682773493621,
    description:
      'Tôn Vũ - Nhà khoa học trẻ tuổi mang theo người máy nano tiến vào thế giới tam quốc, nhưng hình như nơi này cũng không phải tam quốc! Lưu Bị là một tiểu thư khuê các ngoan ngoãn, Quan Vũ là một cô gái biến thái thích đeo râu giả, Trương Phi là cô gái xinh đẹp có tính cách mạnh mẽ và thích uống rượu, Lữ Bố là một tiểu loli uy phong lẫm liệt. Triệu Vân là tiểu loli nhút nhát thích ăn bánh bao, Thái Sử Từ có chứng hoang tưởng... vân vân và vân vân...Đôi lời kinh điển trong truyện:Tôn vũ: “Vũ muội muội, ngươi có thể gỡ bỏ râu giả hay không? Phụ nữ đeo râu thì còn ra thể thống gì nữa!”Quan Vũ: “Nếu Tam muội không uống rượu, ta liền bỏ râu.”Trương Phi: “Nếu Đại tỷ tức giận và mắng chửi người khác, ta sẽ không uống rượu.” Lưu Bị: “Dù các ngươi làm việc gì, đại tỷ cũng không nổi nóng đối với các ngươi.”Lữ Bố: “Ồn ào làm gì? Ta dùng võ tướng kĩ tiễn các ngươi lên trời!”',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDW183I0S0MMwnINs1x1A8LSQ3LSo9Pdkrx1HeEgtw8A33HdIOktMxSswBzE_1yI0NT3QxjIyMAWioSXQ==/manh-nuong-tam-quoc-dien-nghia.jpg',
    listens: 0,
    slug: 'manh-nuong-tam-quoc-dien-nghia',
    status: 'Đang ra',
    title: 'Manh Nương Tam Quốc Diễn Nghĩa',
    totalChaps: 0,
    type: 'story',
    updatedAt: 1682773493621,
  },
  {
    key: '-NUC6RSvzjDU7d-yAtDQ',
    authorId: '-NUC6RX4NCXj9wWKzVQl',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '-NUC6StqGCawxPmkzVMo',
    createdAt: 1682773493627,
    description:
      'Mạnh Xuân Diễm chính là nhân vật nữ được nhắc đến trong truyện Người Đẹp Ngủ Lười Biếng của tác giả Thủy Ngân. Nàng là một cô gái tài năng, sống theo triết lí của riêng mình nhưng lại là một con người vô cùng khiêm tốn.Một cuộc sống tự do tự tại là ước muốn nhỏ bé của cô.. Mặc dù có tài năng nhưng cô chỉ làm việc cho một công ti với chức vụ nhỏ, mức lương đủ sống. Với khả năng khiêm tốn và giấu nghề của mình, cô sống một cuộc sống yên bình, nhẹ nhàng.Nhưng vị sếp thông minh của cô đã nhận ra được khả năng thực sự của cô, hắn bắt cô phải hoàn thành những công việc hóc búa. Đối với cô những công việc đó không khó nhưng cô lại không thích. Cô phải làm gì để trở về với cuộc sống yên ổn trước đây?',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDV1y3M0w1PCcw2LjUL1Q8L9vZ0cw5IdPHz1HeEgtxgX_0c30oTy6rIsDz3cv1yI0NT3QxjIyMAUEISbg==/nguoi-dep-ngu-luoi-bieng.jpg',
    listens: 0,
    slug: 'nguoi-dep-ngu-luoi-bieng',
    status: 'Full',
    title: 'Người Đẹp Ngủ Lười Biếng',
    totalChaps: 11,
    type: 'story',
    updatedAt: 1682773493627,
  },
  {
    key: '-NUC6RT-7yWxGRd11eEL',
    authorId: '-NUC6RXA-3IPOggq0k7P',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '',
    createdAt: 1682773493632,
    description:
      'Truyện Tình Nhân Bé Nhỏ Của Tổng Tài Xấu Xa của tác giả Cao Sơn Vũ Giả kể về câu chuyện của một cô gái chỉ sau tình một đêm cô mới phát hiện ra anh không phải là tổng giám đốc mà chỉ là một nhân viên cao cấp.Khi biết được sự thật cô nhảy dựng lên, không chấp nhận được. Trước thái độ đó của cô, anh tỏ thái độ khinh bỉ và bỏ đi. Nhưng trớ trêu thay, sau vài tình cô phát hiện mình đã mang thai giọt máu của anh.Rồi chuyện gì đến cũng đến, năm năm sau anh trở thành tổng giám đốc thật sự. Trong một lần, anh gặp lại cô và đứa con của mình... Liệu anh có nhận ra cô và sẽ xử lý mọi chuyện như thế nào???',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDW1y13jIgM84yIr_Ar1w8LDjUO9XAOc3fx1HeEgtxUV_3CzMqM8OTSTEtTX_1yI0NT3QxjIyMAXlQSvw==/tinh-nhan-be-nho-cua-tong-tai-xau-xa.jpg',
    listens: 0,
    slug: 'tinh-nhan-be-nho-cua-tong-tai-xau-xa',
    status: 'Full',
    title: 'Tình Nhân Bé Nhỏ Của Tổng Tài Xấu Xa',
    totalChaps: 0,
    type: 'story',
    updatedAt: 1682773493632,
  },
  {
    key: '-NUC6RT5ppADj8YdN8IG',
    authorId: '-NUC6RXHb7MoqwucPfmx',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '',
    createdAt: 1682773493638,
    description:
      'Đối với người phụ nữ, niềm mơ ước là có người đàn ông nào đó cưng chiều mình cả đời. Truyện Cưng Chiều Em Cả Đời của 50 độ U Lam xoay quanh một cô gái có tên là Mạnh Ảnh, cô được Diệc Nhiên cưng chiều, chăm sóc, lo lắng. Do anh quá cưng chiều cô nên mỗi lần cô gặp người đàn ông khác anh lại ghen.Bố mẹ cô cũng vậy cũng yêu nhau sướt mướt nhưng lại không dám bày tỏ tình cảm của mình vì còn e ngại. Liệu kết thúc truyện có được hạnh phúc hay không? ',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDR180L8_FLsvD1LUly1Q8LDjX2KI9Kyojy1HeEgtzEZH1XE4vy0lK_HOdMC_1yI0NT3QxjIyMAW6ISqQ==/cung-chieu-em-ca-doi.jpg',
    listens: 0,
    slug: 'cung-chieu-em-ca-doi',
    status: 'Full',
    title: 'Cưng Chiều Em Cả Đời',
    totalChaps: 0,
    type: 'story',
    updatedAt: 1682773493638,
  },
  {
    key: '-NUC6RMOnHwItrijj1y9',
    authorId: '-NUC6RXOnN9kRbK64EHy',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '-NUC6SmgOGCt6XjWiRAw',
    createdAt: 1682773493683,
    description:
      'Nội dung truyện đặc sắc, tình tiết gây cấn, dù chỉ với mười chương mà truyện Chuyện Tình Của Tổng Tài của Giản Phàm đem alij cho người đọc những điều khó quên..Nhân vật nam chính trong truyện là một người đa tình,cô nào có giỏi đến nhất thì chưa đến ba ngày cũng mất tích.Nhưng cô thì khác, cô được anh giữ lại làm thư kí riêng của mình. Từ ngày đó, anh gặp rất nhiều rắc rối với cô và muốn chấm dứt mối quan hệ này.Nhưng không ngờ một điều, từ ngày xa cô anh lại nhớ cô, lòng nôn nao đi tìm cô khắp ở mọi nơi...Liệu rằng anh co tìm được cô hay không??????????',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDV13X2SAmrLIqKynNO1w8LDvD28QvNSIry1HeEgtzQSP1CJ0-DHMuoKJ_KSP1yI0NT3QxjIyMAZJESvw==/chuyen-tinh-cua-tong-tai.jpg',
    listens: 0,
    slug: 'chuyen-tinh-cua-tong-tai',
    status: 'Full',
    title: 'Chuyện Tình Của Tổng Tài',
    totalChaps: 10,
    type: 'story',
    updatedAt: 1682773493683,
  },
  {
    key: '-NUC6RMVYLaCsaUl5VUZ',
    authorId: '-NUC6RXqmnyhG0q0wnGj',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '',
    createdAt: 1682773493690,
    description:
      'Truyện Tổng Giám Đốc Cho Tôi Mượn Sinh Em Bé của Noãn Đường xoay quanh một cô gái bị mẹ ép hôn vị bà muốn có cháu ngoại. Để chiều lòng mẹ cô cuống cuồng tìm một người đàn ông cô cho là tốt để cưới.Trong đem gió se se lạnh, lòng cô lang lâng hướng ánh nhìn về người đàn ông có vóc dáng hợp với cô. Sau ghi cô bị người đàn ông ăn sạch sẽ từ trên xuống dưới lòng cô lại thấy áy náy buồn bực.Sau đêm đó cô bỏ đi mặc cho người đàn ông đó tìm cô khắp nơi. Người đàn ông đó sẽ ra sao khi biết được sự thật, cô đến với anh trong đêm đó chỉ là để mượn mà thôi. Rồi mọi chuyện sẽ đi đến đâu, anh sẽ chấp nhận như thế nào đây?????',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDT1w2pdCrONAlMM8uy0A8LDvAONorPKnD11HeEgtzwQP1A31yXrKz8knKXfP1yI0NT3QxjIyMAXF8S6Q==/tong-giam-doc-cho-toi-muon-sinh-em-be.jpg',
    listens: 0,
    slug: 'tong-giam-doc-cho-toi-muon-sinh-em-be',
    status: 'Full',
    title: 'Tổng Giám Đốc Cho Tôi Mượn Sinh Em Bé',
    totalChaps: 0,
    type: 'story',
    updatedAt: 1682773493690,
  },
  {
    key: '-NUC6RMfmKi9Hcy0VAHO',
    authorId: '-NSrJb2Uhn0hTKzf6ljf',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '',
    createdAt: 1682773493700,
    description:
      'Thế giới ảo- cầu nối của những trái tim...Truyện Yêu Em Từ Cái Nhìn Đầu Tiên của Cố Mạn kể về câu chuyện tình yêu bắt đầu từ thế giới ảo, nơi giao lưu giữa các bạn trẻ với nhau.Trong thế giới hiện đại, công nghệ phát triển như thế này thì hiện tương game mọc lên như nấm không phải là điều hiếm thấy. Mỗi loại game phù hợp với mỗi lứa tuổi khác nhau, để có trò chơi phù hợp với mình không phải là một điều dễ dàng.Và đâu đó trong thế giới ảo ta lại tìm thấy một tình yêu thực sự, một tình yêu đúng nghĩa. Tình yêu từ cái nhìn đầu tiên.....',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDT1zWL8EtMLi8Nskwu1g8LDjX2DgjzdS301HeEgtwkX_00zxwPd1dDD92Mcv1yI0NT3QxjIyMAV3kSUQ==/yeu-em-tu-cai-nhin-dau-tien.jpg',
    listens: 0,
    slug: 'yeu-em-tu-cai-nhin-dau-tien',
    status: 'Full',
    title: 'Yêu Em Từ Cái Nhìn Đầu Tiên',
    totalChaps: 0,
    type: 'story',
    updatedAt: 1682773493700,
  },
  {
    key: '-NUC6RT6O9axuLFuWypI',
    authorId: '-NUC6RdV-he0sZZ0rWyc',
    categories: ['-NSrJ_yRU38knd4rZG03'],
    chapsId: '-NUC6UG-9MeNpTy-A8hH',
    createdAt: 1682773494113,
    description:
      'Truyện Nương Tử, Nàng Đừng Quá Kiêu Ngạo! của tác giả Dạ Sơ kể về nhân vật nữ chính mới mười sáu tuổi nhưng lại rất tinh nghịch. Muốn hoàn thành tâm nguyện của ông nội mình nàng đành phải xuống núi bảo hộ Lăng đại tiểu thư của Huyến Thải sơn trang.Nàng cải trang tành nam nhi để quậy phá, nhưng không may lúc đó nàng lại gặp Lăng đại tiểu thư , một cô gái có nhan sắc như tiên giáng trần. Trong lúc bất cẫn đùa giỡn, nàng bị Lăng tiểu thư ghi nhớ và trả thù.Ôm hận trong lòng, nàng quyết tâm trả thù, lựa lúc nàng đang tắm để hạ nhục nàng. Chuyện không ngờ xảy đến, người có dung nhan như tiên giáng trần kia lại biến thành một mỹ nam. Chuyện kỳ lạ gì xảy ra thế này, các bạn cùng nhau đón đọc nhé!!!',
    download: 0,
    image:
      'https://static.8cache.com/cover/o/eJzLyTDT1_WpiLT0LvGvdM410A8LDjVO93ENLIjy1HeEgtyMUH2LvKiKZNPE3GyDZP1yI0NT3QxjIyMAW-UStg==/nuong-tu-nang-dung-qua-kieu-ngao.jpg',
    listens: 1,
    slug: 'nuong-tu-nang-dung-qua-kieu-ngao',
    status: 'Full',
    title: 'Nương Tử, Nàng Đừng Quá Kiêu Ngạo!',
    totalChaps: 20,
    type: 'story',
    updatedAt: 1682773494113,
  },
]
